name: 手动转载

on:
  workflow_dispatch:
    inputs:
      url:
        description: '视频链接 (Youtube/Twitch/pixiv 等 yt-dlp 支持链接)'
        required: true
        default: ''
      title:
        description: '标题格式 (如：[转载][{uploader}]{title})'
        required: true
        default: '{title}'
      desc:
        description: '描述格式 (如：{desc})'
        required: true
        default: 'bu'
      tags:
        description: '视频标签 (半角逗号隔开)'
        required: true
        default: '原创,青春'      
      thread:
        description: '视频分区'
        required: true
        type: choice
        options:
         - 日常/21
         - Mugen/19
         - 宅舞/20
         - 日常/21
         - 鬼畜调教/22
         - MAD·AMV/24
         - MMD·3D/25
         - 音MAD/26
         - 原创音乐/28
         - 音乐现场/29
         - VOCALOID·UTAU/30
         - 翻唱/31
         - 完结动画/32
         - 连载动画/33
         - 人文·历史/37
         - 短片·手书·配音/47
         - 演奏/59
         - 网络游戏/65
         - 综艺/71
         - 动物圈/75
         - 美食圈/76
         - 其他国家/83
         - 短片/85
         - 特摄/86
         - 手机平板/95
         - GMV/121
         - 野生技术协会/122
         - 社科人文/124
         - 人力VOCALOID/126
         - 教程演示/127
         - 音乐综合/130
         - 音游/136
         - 明星/137
         - 搞笑/138
         - 欧美电影/145
         - 日本电影/146
         - 华语电影/147
         - 官方延伸/152
         - 国产动画/153
         - 舞蹈综合/154
         - 舞蹈教程/156
         - 美妆/157
         - 服饰/158
         - T台/159
         - 手工/161
         - 绘画/162
         - 运动/163
         - 健身/164
         - 国产原创相关/168
         - 布袋戏/169
         - 资讯/170
         - 电子竞技/171
         - 手机游戏/172
         - 桌游棋牌/173
         - 其他/174
         - 汽车/176
         - 科学·探索·自然/178
         - 军事/179
         - 社会·美食·旅行/180
         - 影视杂谈/182
         - 影视剪辑/183
         - 预告·资讯/184
         - 国产剧/185
         - 海外剧/187
         - 电脑装机/189
         - 摄影摄像/190
         - 影音智能/191
         - 风尚标/192
         - MV/193
         - 电音/194
         - 动态漫·广播剧/195
         - 街舞/198
         - 明星舞蹈/199
         - 中国舞/200
         - 科学科普/201
         - 热点/203
         - 环球/204
         - 社会/205
         - 综合/206
         - 财经/207
         - 校园学习/208
         - 职业职场/209
         - 手办·模玩/210        
      opts:
        description: '其他设置 (如:--original --no-reprint)'
        required: false
        default: '--original'
      ydl_opts:
        description: 'yt-dlp 设置 (默认设置使用 aria2 下载,遇到限流可考虑添加 &format=best)'
        required: false
        default: 'external_downloader=aria2c'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: FedericoCarboni/setup-ffmpeg@v1 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt  
        sudo apt-get install aria2
    - name: Begin Reuploading      
      env:     
        SESSION : ${{ secrets.SESSION }}

             
      run: |
        python -m bilibili_toolman --load 'H4sIAFVe22IC/1WSW2/TMBTHi9abBExjk3gBpGoCRIfomjRpFwQP04aENikgBq9YjuPoeHOTLHY29jAJXlAj+Q3z6fgyOJe1Wx7i4/+52Od3/LP993ytVX3X+pXqkSQ5Y1RotZHR85wKKUZL6dGXRjqolCOc6T96+EtXiShNOCNXWq2DlGmTdGpC1NYhjXDOZZ31uQ5bJvZjKgXBKdUL1csiYntTVxdqqzStsYewQMsIXz0AFlJUF7dN2EMhM0YkCpM5ZrERnjRCUwnl8QXNWMRwwMsTHjfuWNz1FGpj5WmKHbfU05UoqEQsZpJhbgI4N50VavOuP8USqlKU5BlFaZbIhCTcoOuUUMy6dimE/m3oooAn5IyGzWFCD42GOU8ub2m+aqM4udRH377/C/JA9dHNLK61apW/e7s1xJMPJyeH+1/3NfRVtwZ9azamUcGSqqN2jOdUw3PVucA8p1oNLG88DV2bvLAPrOnMGXuu48zMxsaOFezMLK3aaZJJc5n1ckUipcRgo6HptNuggoHaqM077s1GW3GTRm1XmGDb1DPGrYSF6tbkTFCP/khZRksGvZCZ8Wel3zzP+ZzG5WXuNybKM14GNe/FpHaQyZMlnf5HQ/1TzK+0L0p8AeMMnRKp4WWNBobHLdiB9/BaDca2RSaR5djBxCUuDQPbnrl2OPaiyPNwsKfhjQ+jAnZhAOMCrAJs2IbJApwCXB+mC5j5sOeDV8Dbaw3vyiNzIeDZzfR6gopqDOYV0EDno/89fPHifAMAAA==' --seperate_parts --http --cdn ws --youtube "${{ github.event.inputs.url }}" --title "${{ github.event.inputs.title }}" --desc "${{ github.event.inputs.desc }}" --tags "${{ github.event.inputs.tags }}" --thread_id `echo ${{ github.event.inputs.thread }} | cut -d/ -f2` ${{ github.event.inputs.opts}} --opts "${{ github.event.inputs.ydl_opts }}"
